### ISSUE TITLE
AttributeError: /usr/lib/x86_64-linux-gnu/libknot.so: undefined symbol: knot_ctl_alloc

### ISSUE THREAD

**Issue by xavierhardy** [CZ-NIC/jetconf#3]
I am using Ubuntu and I am unable to run Jetconf, even though I have installed `knot`, `libknot1` and `libknot-dev`.

```py
Traceback (most recent call last):
  File "./run.py", line 10, in <module>
    runpy.run_module('jetconf', run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/jetconf/jetconf/__main__.py", line 15, in <module>
    from . import usr_state_data_handlers
  File "/home/user/jetconf/jetconf/usr_state_data_handlers.py", line 8, in <module>
    from .knot_api import KNOT, KnotInternalError
  File "/home/user/jetconf/jetconf/knot_api.py", line 372, in <module>
    KNOT = KnotConfig()
  File "/home/user/jetconf/jetconf/knot_api.py", line 110, in __init__
    super().__init__()
  File "/home/user/jetconf/jetconf/libknot/control.py", line 169, in __init__
    load_lib()
  File "/home/user/jetconf/jetconf/libknot/control.py", line 47, in load_lib
    CTL_ALLOC = LIB.knot_ctl_alloc
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libknot.so: undefined symbol: knot_ctl_alloc
Exception ignored in: <bound method KnotCtl.__del__ of <jetconf.knot_api.KnotConfig object at 0x7ff6353dd320>>
Traceback (most recent call last):
  File "/home/user/jetconf/jetconf/libknot/control.py", line 173, in __del__
    CTL_FREE(self.obj)
AttributeError: 'KnotConfig' object has no attribute 'obj'
```

**Comment by pspirek** [comment]
What version of KnotDNS and what OS do you use?

**Comment by xavierhardy** [comment]
Knot version: 2.1.1
Ubuntu: 16.04 (LTS) codename Xenial
Linux: Kernel 4.4.0

```sh
$ knotd --version
knotd (Knot DNS), version 2.1.1
$ uname -a
Linux user 4.4.0-69-generic #90-Ubuntu SMP Thu Mar 16 16:52:31 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by oerdnj** [comment]
Please update to 2.4.x from here: https://launchpad.net/~cz.nic-labs/+archive/ubuntu/knot-dns
2.1.x release is no longer supported.

**Comment by salzmdan** [comment]
Yes, this old version of Knot doesn't have required control interface!

**Comment by oerdnj** [comment]
The minimum required libknot version should be handled in jetconf, @llhotka please take a look.

**Comment by xavierhardy** [comment]
After updating `knot`, `colorlog` and `yangson`, it starts but then complains that my data store is empty. Could you add a working example configuration and datastore to the repository please? I'm more interested in RESTCONF server than in the DNS.

Thanks anyway

FYI, I got it to run with the following packages installed in my Python virtual environment:
```python
alabaster (0.7.7)
appdirs (1.4.3)
Babel (2.2.0)
colorlog (2.10.0)
docutils (0.12)
h2 (2.2.1)
hpack (2.1.1)
hyperframe (3.2.0)
Jinja2 (2.8)
knot (0.4.0)
MarkupSafe (0.23)
packaging (16.8)
pip (9.0.1)
pkg-resources (0.0.0)
py (1.4.31)
pyaml (16.12.2)
Pygments (2.1)
pyparsing (2.2.0)
pytest (2.8.7)
pytz (2015.7)
PyXB (1.2.5)
PyYAML (3.12)
setuptools (34.3.2)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.3.5)
sphinx-rtd-theme (0.1.9)
wheel (0.30.0a0)
yangson (1.3.4)
```
